[buildPlans.IosevkaPride]
family = "Iosevka Pride"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = false

  [buildPlans.IosevkaPride.variants]
  inherits = "ss14"

    [buildPlans.IosevkaPride.variants.design]
    capital-w = "straight-vertical-sides-serifless"
    m = "short-leg-serifless"
    w = "straight-vertical-sides-serifless"
    y = "cursive-serifless"
    six = "closed-contour"
    nine = "closed-contour"

    [buildPlans.IosevkaPride.variants.italic]
    capital-a = "straight-top-serifed"
    capital-b = "standard-unilateral-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-h = "top-left-serifed"
    capital-j = "serifed"
    capital-k = "straight-top-left-serifed"
    capital-m = "hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "closed-motion-serifed"
    capital-q = "open-swash"
    capital-r = "straight-top-left-serifed"
    capital-s = "bilateral-inward-serifed"
    capital-w = "straight-vertical-sides-motion-serifed"
    capital-x = "straight-motion-serifed"
    capital-y = "straight-motion-serifed"
    g = "double-storey"
    k = "cursive-top-left-serifed"
    m = "short-leg-top-left-serifed"
    w = "straight-vertical-sides-serifless"
    x = "semi-chancery-curly-serifless"
    six = "closed-contour"
    nine = "closed-contour"

[buildPlans.IosevkaPride.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaPride.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaPride.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaPride.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaPride.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaPride.widths.Normal]
shape = 525
menu = 5
css = "normal"

[buildPlans.IosevkaPride.widths.Extended]
shape = 600
menu = 7
css = "expanded"
